### ISSUE TITLE
Question: How to get the context used when calling `RA.answer_question`?

### ISSUE THREAD

**Issue by younes-io** [parthsarthi03/raptor#10]
How to get the context used when calling `RA.answer_question`?

(this should help when testing/debugging/evaluating, etc)

**Comment by 3CE8D2BAC65BDD6AA9** [comment]
Look for def answer_question in the class GPT3TurboQAModel in QAModels.py, then , you can print the context out.

**Comment by parthsarthi03** [comment]
You can use 
```python
context, __ = RA.retrieve(question)
print(context)
```

**Comment by daniyal214** [comment]
But why this does not retrieve the lists of chunks of the original document. Seems returning the summarized version.
Does the QA class answers the question from the summarized text? Instead of the actual content?

What I want is QA model to ask the question from the context which should be the chunks of the actual document not the summarized one. Is this possible?

Because I've been wanting to return the URLs in response, which are receiving broken. When I dig up found out that actual doc is not going to QA model.

Thanks.
